### ISSUE TITLE
Allow alternative searches

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#10]
Provide support for fetching results and facets separately, with adhoc parameters.

**Comment by joemfb** [comment]
Here's a proposal: what if `MLSearchContext.search()` took on optional object argument, to be interpreted as a combined query?

- if the object were an `options` object, it would be combined with `MLSearchContext.getQuery()` in a combined query (ignoring stored options?)

    mlSearch.search({
      options: {
        constraint: [ /* ... */ ]
      }
    })

- if the object were a `search` object, it would be the combined query (facet/qtext state would be ignored)

    mlSearch.search({
      search: {
        query: {
          queries: [ /* .. */ ]
        },
        options: {
          constraint: [ /* ... */ ]
        }
    })

- otherwise the object would be interpreted as the properties of a combined query `options` object

    mlSearch.search({ 'return-facets': false })

Thoughts?

**Comment by grtjn** [comment]
Sounds like a very flexible and extensible approach, I like it! :)

**Comment by joemfb** [comment]
I've worked up an initial implementation, so you can see how it'd work. Running this depends on unreleased changes to ml-common-ng, available here: joemfb/ml-common-ng#dd01b21c

**Comment by grtjn** [comment]
Looks promising! Go ahead and commit if existing functionality doesn't break, easier for me to test published code..

**Comment by joemfb** [comment]
It's in master. If you want to try it, you'll need to be sure and get the latest ml-common-ng (v0.0.6).
