### ISSUE TITLE
Remove the dependency on ngRoute

### ISSUE THREAD

**Issue by paxtonhare** [joemfb/ml-search-ng#17]
For those using angular-ui-router the dependency on ngRoute breaks things.

**Comment by joemfb** [comment]
It's referenced two places:

the `ml-remote-input` here: https://github.com/joemfb/ml-search-ng/blob/b5289fe77a8858c100ea4576961869f1cf2ad0d7/src/directives/ml-remote-input.directive.js#L31?

the MLRemoteInputService here: https://github.com/joemfb/ml-search-ng/blob/b5289fe77a8858c100ea4576961869f1cf2ad0d7/src/ml-remote-input.service.js#L8

but only needed here: https://github.com/joemfb/ml-search-ng/blob/b5289fe77a8858c100ea4576961869f1cf2ad0d7/src/ml-remote-input.service.js#L108

Isn't there a way to programmatically request a service, instead of declaring it a dependency? That could make the route detection feature optional.

Or, the `ml-remote-input` directive could require a path, but that seems like unfortunate coupling. Can `ui-router` be queries for routes the the way ngRoute can be?
