### ISSUE TITLE
make bower.json main not refer to minified files

### ISSUE THREAD

**Issue by paxtonhare** [joemfb/ml-search-ng#42]
from http://bower.io/docs/creating-packages/

- Use source files with module exports and imports over pre-built distribution files.
- **Do not include minified files.**
- Filenames should not be versioned (Bad: package.1.1.0.js; Good: package.js).
- Globs like js/*.js are not allowed.

**Comment by joemfb** [comment]
Sounds good, I'll get to it as soon as I can. Or a PR is welcome ;)

**Comment by joemfb** [comment]
Assuming this is for better compatibility with build tools, `ml-search-ng-tpls.min.js` may pose a problem. It's a separate, optional, complementary "entrypoint" into this component. I'm not currently building an un-minified version, but that could be changed easily enough. The real problem is the rule of only one entrypoint for filetype.

Thoughts?

**Comment by grtjn** [comment]
Hmm, not sure if a main js file with imports/exports works well with things like gulp-concat. We should try that first maybe. Otherwise, you could concat your tpls.js file along with the others, and then minify the total concat. I did that with ml-google-maps-ng as well.

Though, I read now that you shouldn't provide a concat/dist as main either.. :-P
