### ISSUE TITLE
Don't suppress options request param for adhoc searches

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#86]
Related to #83, where values() was not passing through the options request param in certain cases, adhoc search is doing that too. It should always be passed through, unless you add a way to pass in params, and provide an override for that as well. Passing in extra/adhoc (request) params would be nice as well.

**Comment by joemfb** [comment]
Not passing the options param is actually by design: the logic is spelled out here: https://joemfb.github.io/ml-search-ng/MLSearchContext.html#search. However, the more I think about it, the less it seems like a valid use-case. The built query will almost always depend on the stored options, so the only use-case for withholding the options param would be some kind of dynamic constraint substitution. That seems like an unlikely requirement, so this "feature" is probably more trouble than it's worth.
